name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

    - name: Deploy to Server
      run: |
        ssh -p 32121 -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} <<EOF
          sudo su -
          cd /opt/NetRoomManager/
          git fetch --all
          git reset --hard origin/main
          mvn clean package
          /opt/apache-tomcat-9.0.82/bin/shutdown.sh
          rm -rf /opt/apache-tomcat-9.0.82/webapps/ROOT*
          cp target/ROOT.war /opt/apache-tomcat-9.0.82/webapps/
          /opt/apache-tomcat-9.0.82/bin/startup.sh
        EOF
